name: bibTexConverter
channels:
  - defaults
  - conda-forge
dependencies:
  - conda-libmamba-solver
  - python=3.12
  - scikit-learn=1.4.2
  - pandas=2.2
  - tesseract=5.2
  - requests=2.31
  - pyyaml=6.0
  - pytest=7.4
  - black=24.3
  - flake8=7.0
# Weitere Kandidaten für Pakete, die wir brauchen könnten sein:
# pytoorch bzw tensorflow (für NER oder LLMs)
# ggf. eine spezialisierte Bibliothek für hyperparameter Optimierung wie optuna oder hyperopt
# dvc (Versionierung von Daten und Verknüpfung der Versionen mit den Source-Versionen über git)
#
# scraping:
# beautiful soup (für Web-Scraping)
# pdfplumber (für pdf-Scraping)
#
# Benutzeroberfläche:
# fastapi (für einfache REST-APIs)
# tkinter (falls wir standalone-GUIs entwickeln)
# flask (für WEB-Anwendungen - aber ggf. reicht das alleine nicht um copy-paste-fähige Frontends zu entwickeln)
#
# Rein für die Entwicklung könnten wir vielleicht folgendes benötigen:
# jupyter-lab
# spyder (einfache Entwicklungsumgebung)
