name: bibTexConverter
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - scikit-learn=1.4.2
  - pandas=2.2.1
  - tesseract=5.2.0
  - requests=2.27.1
  - pytest=7.4.0
  - black=19.3b
  - flake8=3.8.3
# Weitere Kandidaten für Pakete, die wir brauchen könnten sein:
# beautiful soup (für Web-Scraping)
# pdfplumber (für pdf-Scraping)
# pytoorch bzw tensorflow (für NER oder LLMs)
# fastapi (für einfache REST-APIs)
# tkinter (falls wir standalone-GUIs entwickeln)
# flask (für WEB-Anwendungen - aber ggf. reicht das alleine nicht um copy-paste-fähige Frontends zu entwickeln)
# yaml (zum Lesen/Schreiben von yaml-Dateien zur Konfiguration - z.B. zur Konfiguration der Verarbeitungs-Pipeline)
