name: bibTexConverter
channels:
  - defaults
  - conda-forge
dependencies:
  - conda-libmamba-solver
  - python=3.12
  - scikit-learn=1.4.2
  - pandas=2.2
  - tesseract=5.4
  - requests=2.31
  - pyyaml=6.0
  - pytest=7.4
  - black=24.3
  - flake8=7.0
  - flask=3.0.3
  - spacy=3.7.5
  - pybtex=0.24.0
  
