name: bibTexConverter
channels:
  - defaults
  - conda-forge
dependencies:
  - conda
  - python_abi=3.10
  - python=3.10.1
  - pandas=2.2
  - tesseract=5.4
  - pyyaml=6.0
  - flask=3.0.3
  - pybtex=0.24.0
  - pytorch
  - transformers
  - pytesseract=0.3.10
  - pillow=10.4.0
